--
-- Create table tbl_trackPoint in data base
-- Created: 8.12.2017 - Daniel Leutwyler
--

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Table structure for table `tbl_trackpoint`
--
CREATE TABLE IF NOT EXISTS `tbl_trackPoints` (
  `tptId` int(11) NOT NULL COMMENT 'Autogenerated trackpoint ID', 
  `tptNumber` int(11) NOT NULL COMMENT 'Number of trackpoints within a track (starting at 0)',
  `tptTrackFID` int(11) NOT NULL COMMENT 'Foreign key reference to track (tbl_tracks)',
  `tptLat` double DEFAULT NULL COMMENT 'Latitude as defined in GPX specs',
  `tptLon` double DEFAULT NULL COMMENT 'Longitude as defined in GPX specs', 
  `tptEle` int(11) DEFAULT NULL COMMENT 'Elevation as defined in GPX specs', 
  `tptTime` datetime DEFAULT NULL COMMENT 'Start time of GPX track (gpx->metadata->time)'
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4;  

--
-- Indexes for table `tbl_segments`
--
ALTER TABLE `tbl_trackPoints`
  ADD PRIMARY KEY (`tptId`) USING BTREE;

--
-- AUTO_INCREMENT for table `tbl_segments`
--
ALTER TABLE `tbl_trackPoints`
  MODIFY `tptId` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=0;

